name: BUILD PKG

on:
  workflow_dispatch:
  
jobs:
  buildAUR:
    strategy:
      matrix:
        repos: [pwvucontrol, matugen-bin, chromium-widevine]

      fail-fast: false
      
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - uses: ./build-aur-action
      with:
        repo-name: ${{ matrix.repos }}
        preinstallPkgs: ${{ matrix.preinstall_pkgs }}
    
    - uses: actions/upload-artifact@v4
      with:
        path: ./*/*.pkg.tar.zst
        name: ${{ matrix.repos }}
        if-no-files-found: error
  
  buildNonAUR:
    strategy:
      matrix:
        pkgdir: [sing-box]

      fail-fast: false
      
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - uses: ./build-nonaur-action
      with:
        pkgdir: ${{ matrix.pkgdir }}
    
    - uses: actions/upload-artifact@v4
      with:
        path: ./build-nonaur-action/*/*.pkg.tar.zst
        name: ${{ matrix.pkgdir }}
        if-no-files-found: error

  uploadToReleases:      
    runs-on: ubuntu-latest
    if: always()
    needs: [buildAUR, buildNonAUR]

    steps:
      - uses: actions/checkout@v4
      
      - name: Download all build artifacts
        uses: actions/download-artifact@v4
        with:
          path: ./downloaded_artifacts
        id: download

      - name: Show files
        run: ls -R ./downloaded_artifacts
      
      - name: Create DB and prepare upload packages
        uses: ./create-db-and-upload-action
        with:
          repo_name: vifly
          local_path: ./downloaded_artifacts

      - name: Delete existing release
        run: gh release delete packages -y || true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create/Update GitHub Release and upload assets
        uses: ncipollo/release-action@v1
        with:
          allowUpdates: true
          tag: "packages"
          artifacts: "./upload_packages/*.files,./upload_packages/*.db,./upload_packages/*.tar.gz,./downloaded_artifacts/*/*/*.pkg.tar.zst"
          token: ${{ secrets.GITHUB_TOKEN }}
